name: pretest_aksamedia
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get_cli: ^1.8.1
  get: 4.6.6
  flutter: 
    sdk: flutter
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.2.0+3
 

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/

